spring:
  application:
    name: payment-quick-sample
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment_sample?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root2020
mybatis:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
